<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="AllContacts.aspx.cs" Inherits="netContactBookApplication.AllContacts" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
    </head>
<body>
    <form id="form1" runat="server">
        <div>
        </div>
            <asp:GridView ID="GridView1" runat="server" DataKeyNames="ID" OnRowDataBound="OnRowDataBound" OnRowEditing="OnRowEditing" OnRowCancelingEdit="OnRowCancelingEdit" OnRowUpdating="OnRowUpdating" OnRowDeleting="OnRowDeleting" EmptyDataText="No records has been added." AutoGenerateEditButton="True" AutoGenerateDeleteButton="True" Height="267px"   Width="1114px">
                <Columns>
                    
                </Columns>
        </asp:GridView>
       
    </form>
</body>
</html>
